In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2023-01-11 09:56:24.086950: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


2.4.0


# Tensors & Other Data Structures

## Create a Tensor

In [2]:
# Create a constant tensor

const_tensor = tf.constant(value=4, dtype=None, shape=(3,2,5), name="const_tensor")
const_tensor

2023-01-11 09:56:29.818420: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-01-11 09:56:29.869848: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-01-11 09:56:30.010815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-11 09:56:30.028945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 970 computeCapability: 5.2
coreClock: 1.253GHz coreCount: 13 deviceMemorySize: 3.94GiB deviceMemoryBandwidth: 208.91GiB/s
2023-01-11 09:56:30.028967: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-01-11 09:56:30.111308: I tensorflow/stream_executor/platform/def

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]], dtype=int32)>

In [3]:
# Create a all zero (one) constant tensor
# By default, both use tf.float32 as the data type
zeros_tensor = tf.zeros(shape=(3,2,5))
ones_tensor = tf.ones(shape=(3,2,5))

print(zeros_tensor)
print()
print(ones_tensor)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 2, 5), dtype=float32)


In [4]:
# Create a Tensor from Numpy or Python objects

np_array = np.array([[[2.,3.,4.],
                      [23.,34.,1.,]],
                     [[6.,23.,12.],
                      [44.,73.,121.,]],
                     [[5.,9.,0.],
                      [12.,-34.,-1.,]],
                    ])

t_np = tf.convert_to_tensor(np_array, dtype=tf.float32)
t_np

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[  2.,   3.,   4.],
        [ 23.,  34.,   1.]],

       [[  6.,  23.,  12.],
        [ 44.,  73., 121.]],

       [[  5.,   9.,   0.],
        [ 12., -34.,  -1.]]], dtype=float32)>

## Tensor Indexing

In [5]:
# Numpy style indexing
# : means up to certain index on a dimension
# ... (Ellipsis) means all dimensions that are omitted
print(t_np[:, :, 1:])
print()
print(t_np[..., 1, :])
print()
print(t_np[..., 1])
print()
# add a newaxis to keep the dimensions of the origial tensor
print(t_np[..., 1, tf.newaxis])

tf.Tensor(
[[[  3.   4.]
  [ 34.   1.]]

 [[ 23.  12.]
  [ 73. 121.]]

 [[  9.   0.]
  [-34.  -1.]]], shape=(3, 2, 2), dtype=float32)

tf.Tensor(
[[ 23.  34.   1.]
 [ 44.  73. 121.]
 [ 12. -34.  -1.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[  3.  34.]
 [ 23.  73.]
 [  9. -34.]], shape=(3, 2), dtype=float32)

tf.Tensor(
[[[  3.]
  [ 34.]]

 [[ 23.]
  [ 73.]]

 [[  9.]
  [-34.]]], shape=(3, 2, 1), dtype=float32)


## Math Operations

- Usually 3 ways to call
    - Python Operator: `+`, `-`, `*`, `/`, `//`, `**`, `%`, `@`(matrix multiplication)
    - `tf` API aliases: `tf.add()`, `tf.transpose()` (not complete, e.g., there is no alias for `tf.math.log`)
    - `tf.math` APT: `tf.math.log`, `tf.math.matmul()`

## Tensors are Immutable

In [6]:
# Tensors are immutable
# Indexing and operations create a new tensor

print(id(t_np))
print(id(t_np[:,1,:]))
print(id(t_np + 100.))

140688835708880
140688888117200
140688888117376


## Data Types

### Data Type Conversion
- TensorFlow does not automatically convert data types during operations.
- An exeption was raised if the data types are not compatible with the operation.
- `cast` can be used to convert data types.

In [7]:
t1 = tf.constant(40, dtype=tf.float64)
t2 = tf.constant(20, dtype=tf.float32)

try:
    t1 + t2
except tf.errors.InvalidArgumentError:
    print("A tensor of type float64 cannot be added with one of type float32")
    
tf.add(t2, tf.cast(t1, tf.float32))

A tensor of type float64 cannot be added with one of type float32


<tf.Tensor: shape=(), dtype=float32, numpy=60.0>

## Data Structures other than Tensor

- Variables
    - Since `tf.Tensor` is immutable and cannot be used as weight matrices, `tf.Variable` is needed.
    - A variable object can be updated using `assign()` or `scatter_update()`.
- `tf.SparseTensor`, opertaion API: `tf.sparse`
- `tf.TensorArray`: list of tensors with same shape and data types.
- `tf.RaggedTensor`: Static list of lists of tensors with the same shape and data types. Operation API: `tf.ragged`.
- String tensors: tensor of data type `tf.string`
- Sets: a vector in a tensor's last axis. `tf.sets`
- Queues: tensor storage, batching and shuffling: `tf.queue`

# Customizations
- One can customize a lot of compotent of a deep learning models
    - Loss fuctions
    - Activation functions
    - Initializers
    - Regularizers
    - Constraints
- 2 ways to implement the customizations
    - Simple way when no hyperparameters need to be saved: write a Python function to do it.
        - Make the function available to the runtime when loading the model
    - Full way when hyperparamters need to be saved: write a Python class to do it.
        - Make sure subclassing the proper TensorFlow class.
        - Make the class available to the runtime when loading the model
        - Map the class name with the actual class in `load_model`.
- Try to always use TensorFlow operations to take advantage of the GPU computing.

## Custom Loss Functions

In [8]:
# Simple way (functional) to implement Huber loss

def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abd(error) - 0.5
    return tf.where(is_small_error, square_loss, linear_loss)

# # Then to use it
# model.compile(loss=huber_fn, optimizer="nadam")
# model.fit(X_train, y_train, ...)


# If hyperparameters needs to be saved, then use subclass

class HuberLoss(tf.keras.losses.Loss):
    
    def __init__(self, threshold=1.0, **kwargs):
        self.threshold = threshold
        super().__init__(**kwargs)
        
    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.threshold
        squared_loss = tf.square(error) / 2
        linear_loss = self.threshold * tf.abd(error) - self.threshold**2 / 2
        return tf.where(is_small_error, square_loss, linear_loss)
    
    def get_config(self):
        """
        A get_config() method is required for a instance to use save() method and tf.keras.model.load_model()
        Otherwise only save_weights() and load_weights() can be used.
        """
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}
    
# # Use the above class
# model.compile(loss=HuberLoss(2.), optimizer="nadam")

# # When model is loaded
# model = keras.models.load_model("my_model_with_a_custom_loss_class.h5", custom_objects={"HuberLoss": HuberLoss})

## Custom Layer Components: Initializers, Regularizers, and Constraints

In [9]:
# Functional approach, no hyperparameter is needed

# Equivalent to keras.initializers.glorot_normal()
def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)

# Equivalent to keras.regularizers.l1(0.01)
def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))

# Equivalent to keras.constraints.nonneg() or tf.nn.relu()
def my_positive_weights(weights):
    return tf.where(weights < 0., tf.zeros_like(weights), weights)


# If writing a class to include hyperparameters
# An example of regularizer, others are similar
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    
    def __init__(self, factor):
        self.factor = factor
        
    def __call__(self, weights):
        return tf.reduce_sum(tf.abs(self.factor * weights))
    
    def get_config(self):
        return {"factor": self.factor}

## Custom Activation Function

In [10]:
# Equivalent to keras.activations.softplus() or tf.nn.softplush()
def my_softplus(z):
    return tf.math.log(tf.exp(z) + 1.0)

# If hyparameters are needed, then create a custom layer

## Custom Metrics
- Streaming Metrics (Stateful Metrics) keep track of accumulative metric values and the total instance counts. They are gradually updated for each batch.

In [11]:
# Example of custom HuberMetric

def create_huber(threshold=1.0):
    # A function that generate a huber_fn with a certain value of threshold
    
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        square_loss = tf.square(error) / 2
        linear_loss = threshold * tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

        
class HuberMetric(tf.keras.metrics.Metric):
    "Custome Metric based on Huber loss formula"
    
    def __init__(self, threshold=1.0, **kwargs):
        
        super().__init__(**kwargs) # handles parent arguments passed in **kwargs
        self.threshold = threshold
        
        # generate huber with dynamic threshold value
        self.huber_fn = create_huber(threshold)
        
        # add 2 tf.Variables using add_weight
        # total is the cumulative metric value
        # count is the cumulative instance counts
        self.total = self.add_weight("total", initializer="zeros")
        self.count = self.add_weight("count", initializer="zeros")
        
    def update_state(self, y_true, y_pred, sample_weight=None):
        "Used when the instance of this class is used as a function to update the total and count values"
        metric = self.huber_fn(y_true, y_pred)
        self.total.assign_add(tf.reduce_sum(metric))
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))
        
    def result(self):
        return self.total / self.count
    
    def get_config(self):
        """
        A get_config() method is required for a instance to use save() method and tf.keras.model.load_model()
        Otherwise only save_weights() and load_weights() can be used.
        """
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

## Custom Layers
- Layers without trainable variables (weights): create a function and wrap it with `tf.keras.layers.Lambda`
- Layers with trainable variables (weights): create a subclass of `tf.keras.layers.Layer`
- Layers that behave differently in training and scoring (with a training=True or False option). For example `Dropout` or `BatchNormalization`.

In [15]:
# A simple custom layer without trainable weights
# Equivalent to using activation=tf.exp or activation=keras.activations.exponential or activation="exponential"
# Can be used as a output layer when the targets have different scales

exponential_layer = tf.keras.layers.Lambda(lambda x: tf.exp(x))


# A custom Dense layer
class MyDense(tf.keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.unit = units
        # Turn keywords into actual activation functions
        self.activation = tf.keras.activations.get(activation)
        
    def build(self, batch_input_shape):
        self.kernel = self.add_weight(name="kernel", 
                                      shape=[batch_input_shape[-1], self.units],  
                                      initializer="glorot_normal")
        self.bias = self.add_weight(name="bias", shape=[self.units], initializer="zeros")
        super().build(batch_input_shape)
        
    def call(self, X):
        return self.activation(X @ self.kernel + self.bias)
    
    def compute_output_shape(self, batch_input_shape):
        return tf.TensorShape(batch_input_shape.as_list()[:-1] + [self.units])
    
    def get_config(self):
        """
        A get_config() method is required for a instance to use save() method and tf.keras.model.load_model()
        Otherwise only save_weights() and load_weights() can be used.
        """
        base_config = super().get_config()
        return {**base_config, "units": self.units, "activation": keras.activations.serialize(self.activation)}
    

# A custom multilayer that concatenate 2 layers and output 3 layers
class MyMultiLayer(tf.keras.layers.Layer):
    def call(self, X):
        X1, X2 = X
        return [X1 + X2, X1 * X2, X1 / X2]
    
    def compute_output_shape(self, batch_input_shape):
        b1, b2 = batch_input_shape
        return [b1, b1, b1]

    
# A custom layer with different behavior in training and scoring
# Equivalent to tf.keras.layers.GaussianNoise
class MyGuassianNoise(tf.keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super().__init__(**kwargs)
        self.stddev = stddev
        
    def call(self, X, training=None):
        if training:
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        else:
            return X
    
    def compute_output_shape(self, batch_input_shape):
        return batch_input_shape

## Custom Models
- `tf.keras.Model` is a subclass of `tf.keras.layers.Layer`, 
    - but with more attributes like `compile()`, `fit()`, `evaluate()`, `predict()`, `get_layers()`, and `save()`.
    - `save() method` is supported by `tf.keras.models.load_model()` and `tf.keras.model.clone_model()`.

In [17]:
# An example of custom model that uses a "residual block"


class ResidualBlock(tf.keras.layers.Layer):
    """
    A residual block is a model structure that
        1. consists of n_layers dense layers with n_neurons for each layer
        2. appends the input to the output
    """
    def __init__(self, n_layers, n_neurons, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [tf.keras.layers.Dense(n_neurons, activation="elu", 
                                             kernel_initialization="he_normal") 
                       for _ in range(n_layers)]
        
    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        return inputs + Z
    
class ResidualRegressor(tf.keras.Model):
    """
    A model structure that consist of instances of ResidualBlock and other dense layers
    """
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden1 = tf.keras.layers.Dense(30, activation="elu", kernel_initializer="he_normal")
        self.block1 = ResidualBlock(2, 30)
        self.block2 = ResidualBlock(2, 30)
        self.out = keras.layers.Dense(output_dim)
        
    def call(self, inputs):
        Z = self.hidden1(inputs)
        for _ in range(1 + 3):
            Z = self.block1(Z)
        Z = self.block2(Z)
        return self.out(Z)

## Other Customizations
- Create a custom model containing a loss/metric function that use the values generated during the training.
- Custom training loop (fit()) method that can use multiple optimizers

# TensorFlow Graphs

## Functions, Autograph, Tracing

...To be continued...